### ISSUE TITLE
seems that it not supports fontawesome!?

### ISSUE THREAD

**Issue by 4URGB** [riesinger/pure-css-tooltips-tutorial#1]

**Comment by riesinger** [comment]
Yes, I haven't used fontawesome in ages, but IIRC, fontawesome's `<i>` tags use the `::before` pseudo-element to display the icons. You might be able to change the tooltip CSS to use the `::after` element.

**Comment by riesinger** [comment]
I am marking this as wontfix since switching to the `::after` element probably will break some other icon font out there and it's not too hard to do on your own
